@startuml

left to right direction

skinparam packageStyle rectangle

actor Secretário
actor Funcionário
actor Médico

Funcionário <|-- Secretário

rectangle SUS {
  Secretário -- (Cadastrar médico)
  Secretário -- (Cadastrar unidade de saúde)
  Secretário -- (Escalar médicos)
  Secretário -- (Supervisionar sistema)
  (Consultar agenda) -- Médico
  Funcionário -- (Agendar consulta)
  (Cadastrar cidadão) .> (Agendar consulta) : <<extends>>
}

@enduml
