@startuml

left to right direction

skinparam packageStyle rectangle

actor Secretário
actor Funcionário
actor Médico

rectangle SUS {
  Secretário -- (Cadastrar médico)
  Secretário -- (Cadastrar unidade de saúde)
  Secretário -- (Escalar médico)
  Secretário -- (Supervisionar sistema)
  (Consultar agenda) -- Médico
  Funcionário -- (Cadastrar cidadão)
  Funcionário -- (Agendar consulta)
  (Agendar consulta) .> (Cadastrar cidadão) : <<include>>
}

@enduml
