@startuml

class Consulta {
  id: Integer
  unidade: Unidade
  medico: Medico
  cidadao: Cidadao
  getConsulta()
  setConsulta()
}

class Unidade {
  id : Integer
  nome: String
  endereco: String[]
  estrutura: String[]
  getUnidade()
  setUnidade()
}

class Medico {
  crm : Integer
  nome: String
  especialidade: String
  unidade: Unidade
  getMedico()
  setMedico()
}

class Cidadao {
  cpf : Integer
  nome: String
  endereco: String[]
  getCidadao()
  setCidadao()
}

Consulta -- Medico
Consulta -- Cidadao
Medico -- Unidade

@enduml
